#!/usr/bin/env python3
"""Minimal CLI to transcribe an audio file to SRT using faster-whisper."""
from utils import Timer, Logger, load_config, sanitize_filename, setup_file_logging, add_handler_to_logger, remove_handler_from_logger
_config = load_config()
timer = Timer()
logger = Logger()  # Initialize without debug
# Read debug setting from config file
debug_setting = _config.get("logger", "debug", fallback="False")
logger.debug_enabled = debug_setting.lower() in ("true", "1", "yes")

logger.basic("-- Importing Global modules --")
import argparse
from pathlib import Path
import sys
import os
import subprocess
import logging
import gc
import warnings
import configparser
import json
import tempfile
import re
from dataclasses import dataclass
from datetime import datetime
timer.checkpoint("Global Modules loaded")
logger.basic("-- Completed Importing Global Modules --")

logger.basic("-- Loading Faster-Whisper --")
from faster_whisper import WhisperModel
logger.debug(timer.checkpoint("Faster-Whisper loaded"))
logger.basic("-- Faster-Whisper loaded --")

# Initialize file logging
log_dir_str = _config.get("logger", "log_dir", fallback=None)
log_dir = Path(log_dir_str) if log_dir_str else None
general_handler, current_video_handler = setup_file_logging(log_dir)
if general_handler:
	add_handler_to_logger(logger, general_handler)
	logger.basic(f"-- File logging enabled: {log_dir} --")

@dataclass
class TranscribedSegment:
	"""Unified segment for SRT output, with optional speaker label."""
	start: float
	end: float
	text: str
	speaker: str | None = None


# ============================================================================
# PRIVATE HELPERS
# ============================================================================

def _format_srt_timestamp(seconds: float) -> str:
	"""Convert float seconds to SRT timestamp (HH:MM:SS,mmm)."""

	millis = int(round(seconds * 1000))
	hours, millis = divmod(millis, 3_600_000)
	minutes, millis = divmod(millis, 60_000)
	secs, millis = divmod(millis, 1_000)
	return f"{hours:02}:{minutes:02}:{secs:02},{millis:03}"


def _format_ass_timestamp(seconds: float) -> str:
	"""Convert float seconds to ASS timestamp (H:MM:SS.cc)."""
	centis = int(round(seconds * 100))
	hours, centis = divmod(centis, 360000)
	minutes, centis = divmod(centis, 6000)
	secs, centis = divmod(centis, 100)
	return f"{hours}:{minutes:02}:{secs:02}.{centis:02}"


def _write_srt(segments: list[TranscribedSegment], output_path: Path) -> None:
	"""Write segments to SRT, optionally prefixing speaker labels."""
	with output_path.open("w", encoding="utf-8") as fh:
		for idx, seg in enumerate(segments, start=1):
			start = _format_srt_timestamp(seg.start)
			end = _format_srt_timestamp(seg.end)
			text = seg.text.strip()
			if seg.speaker:
				text = f"[{seg.speaker}] {text}"
			fh.write(f"{idx}\n{start} --> {end}\n{text}\n\n")


def _write_ass(segments: list[TranscribedSegment], output_path: Path, mkv_title: str = "Unknown", mkv_resolution: tuple[int, int] = (1920, 1080)) -> None:
	"""Write segments to ASS format with proper header and styling."""
	play_res_x, play_res_y = mkv_resolution
	
	# Scale font sizes based on actual PlayRes
	font_size = int(38 * play_res_y / 1080)  # ClosedCaptions: 38pt at 1080p
	signs_font_size = int(44 * play_res_y / 1080)  # Signs: 44pt at 1080p (slightly larger)
	
	# Build ASS header
	ass_header = f"""[Script Info]
; Script generated by transcribe_faster_whisper.py
Title: {mkv_title}
ScriptType: v4.00+
Collisions: Normal
PlayResX: {play_res_x}
PlayResY: {play_res_y}
Timer: 100.0000

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,{font_size},&H00FFFFFF,&H000000FF,&H64000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: ClosedCaptions,Arial,{font_size},&H00FFFFFF,&H000000FF,&H64000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: Signs,Arial,{signs_font_size},&H00FFFFC8,&H000000FF,&H64000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,8,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
	
	with output_path.open("w", encoding="utf-8") as fh:
		fh.write(ass_header)
		for idx, seg in enumerate(segments, start=0):
			start = _format_ass_timestamp(seg.start)
			end = _format_ass_timestamp(seg.end)
			text = seg.text.strip()
			# For ASS format, replace newlines with \N (ASS newline code)
			text = text.replace('\n', '\\N')
			if seg.speaker:
				text = f"[{seg.speaker}] {text}"
			# ASS event format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
			fh.write(f"Dialogue: 0,{start},{end},ClosedCaptions,,0,0,0,,{text}\n")


def _write_words_json(segments, output_path: Path) -> None:
	words = []
	for seg in segments:
		if getattr(seg, "words", None):
			for w in seg.words:
				words.append(
					{
						"word": w.word,
						"start": w.start,
						"end": w.end,
						"probability": getattr(w, "probability", None),
					}
				)

	if not words:
		return

	import json
	with output_path.open("w", encoding="utf-8") as fh:
		json.dump(words, fh, ensure_ascii=False, indent=2)


def _merge_overlapping_segments(segments: list[TranscribedSegment]) -> list[TranscribedSegment]:
	"""Merge segments with overlapping time ranges into multi-line subtitles."""
	if not segments:
		return segments
	
	merged = []
	current_group = [segments[0]]
	
	for seg in segments[1:]:
		# Check if this segment overlaps with any in current group
		overlaps = any(seg.start < existing.end for existing in current_group)
		
		if overlaps:
			current_group.append(seg)
		else:
			# Finalize current group
			if len(current_group) == 1:
				merged.append(current_group[0])
			else:
				# Merge overlapping segments into one with multi-line text
				start = min(s.start for s in current_group)
				end = max(s.end for s in current_group)
				text = "\n".join(s.text for s in current_group)
				merged.append(TranscribedSegment(start=start, end=end, text=text, speaker=None))
			
			current_group = [seg]
	
	# Handle last group
	if len(current_group) == 1:
		merged.append(current_group[0])
	else:
		start = min(s.start for s in current_group)
		end = max(s.end for s in current_group)
		text = "\n".join(s.text for s in current_group)
		merged.append(TranscribedSegment(start=start, end=end, text=text, speaker=None))
	
	return merged


def _get_mkv_title(video_path: Path) -> str:
	"""Extract title metadata from MKV file using ffprobe.
	
	Returns title if found, otherwise returns filename without extension.
	"""
	try:
		result = subprocess.run(
			[
				"ffprobe", "-v", "quiet",
				"-print_format", "json",
				"-show_format",
				str(video_path)
			],
			capture_output=True,
			text=True,
			timeout=10
		)
		if result.returncode == 0:
			data = json.loads(result.stdout)
			if 'format' in data and 'tags' in data['format']:
				title = data['format']['tags'].get('title')
				if title:
					return title
	except Exception as e:
		logger.debug(f"Error extracting MKV title: {e}")
	
	# Fallback to filename without extension
	return video_path.stem


def _get_mkv_resolution(video_path: Path) -> tuple[int, int]:
	"""Extract video resolution from MKV file using ffprobe.
	
	Returns (width, height) tuple. Defaults to (1920, 1080) if not found.
	"""
	try:
		result = subprocess.run(
			[
				"ffprobe", "-v", "quiet",
				"-print_format", "json",
				"-show_streams",
				str(video_path)
			],
			capture_output=True,
			text=True,
			timeout=10
		)
		if result.returncode == 0:
			data = json.loads(result.stdout)
			for stream in data.get('streams', []):
				if stream.get('codec_type') == 'video':
					width = stream.get('width')
					height = stream.get('height')
					if width and height:
						return (width, height)
	except Exception as e:
		logger.debug(f"Error extracting MKV resolution: {e}")
	
	# Default to 1080p for font sizing
	return (1920, 1080)


def _extract_subtitle_from_mkv(video_path: Path, name_match: str) -> Path | None:
	"""Extract first text subtitle track from MKV matching a pattern (case-insensitive).
	
	Uses mkvmerge to identify tracks, then mkvextract to extract the matched subtitle.
	Supported formats: S_TEXT/UTF8 (SRT), S_TEXT/ASS (ASS), S_TEXT/SSA (SSA).
	
	Args:
		video_path: Path to MKV file
		name_match: Partial substring to match against subtitle track name (case-insensitive)
		
	Returns:
		Path to extracted subtitle file, or None if no match found
	"""
	SUBTITLE_CODECS = {
		"S_TEXT/UTF8": "srt",
		"S_TEXT/ASS": "ass",
		"S_TEXT/SSA": "ssa",
	}
	
	try:
		# Get track information from MKV
		result = subprocess.run(
			["mkvmerge", "-J", str(video_path)],
			capture_output=True,
			text=True,
			timeout=60,  # Increased for large files on slower storage
			check=True
		)
		info = json.loads(result.stdout)
		tracks = info.get('tracks', [])
		
		# Find first text subtitle track matching pattern
		target_track = None
		for track in tracks:
			if track.get('type') != 'subtitles':
				continue
			codec_id = track.get('properties', {}).get('codec_id', '')
			if codec_id not in SUBTITLE_CODECS:
				continue  # Skip image-based subtitles (pgs, vobsub, etc)
			
			track_name = track.get('properties', {}).get('track_name', '')
			if name_match.lower() in track_name.lower():
				target_track = track
				break
		
		if target_track is None:
			logger.debug(f"No subtitle track matching '{name_match}' found in {video_path.name}")
			return None
		
		# Extract the subtitle
		track_id = target_track['id']
		codec_id = target_track.get('properties', {}).get('codec_id', '')
		ext = SUBTITLE_CODECS.get(codec_id, 'ass')
		
		output_path = video_path.parent / f"{video_path.stem}_{name_match}.{ext}"
		
		subprocess.run(
			["mkvextract", "tracks", str(video_path), f"{track_id}:{output_path}"],
			capture_output=True,
			timeout=30,
			check=True
		)
		
		logger.debug(f"Extracted '{name_match}' subtitle to {output_path.name}")
		return output_path
	
	except subprocess.TimeoutExpired:
		logger.debug(f"Timeout extracting subtitle from {video_path.name}")
		return None
	except subprocess.CalledProcessError as e:
		logger.debug(f"Error extracting subtitle: {e.stderr}")
		return None
	except (json.JSONDecodeError, KeyError) as e:
		logger.debug(f"Error parsing MKV info: {e}")
		return None
	except Exception as e:
		logger.debug(f"Unexpected error extracting subtitle: {e}")
		return None


def _merge_ass_subtitles(primary_ass: Path, secondary_ass: Path, output_path: Path) -> None:
	"""Intelligently merge two ASS subtitle files.
	
	When secondary is native ASS with hardcoded positions (clips, pos, move),
	uses secondary's PlayRes and scales primary's font sizes to match.
	This preserves animated signs/titles that rely on specific coordinates.
	
	Args:
		primary_ass: Main ASS file (e.g., transcription output) - font sizes will be scaled
		secondary_ass: Secondary ASS file (e.g., extracted Signs) - PlayRes preserved
		output_path: Output file path
	"""
	try:
		# Parse both files
		primary_header, primary_dialogues = _parse_ass_file(primary_ass)
		secondary_header, secondary_dialogues = _parse_ass_file(secondary_ass)
		
		# Parse PlayResY from both headers
		def get_play_res_y(header_lines):
			for line in header_lines:
				if line.startswith("PlayResY:"):
					try:
						return int(line.split(":")[1].strip())
					except (ValueError, IndexError):
						pass
			return 1080
		
		primary_res_y = get_play_res_y(primary_header)
		secondary_res_y = get_play_res_y(secondary_header)
		
		# Calculate scale factor for primary styles
		scale = secondary_res_y / primary_res_y if primary_res_y else 1.0
		
		# Extract and scale primary styles
		primary_styles = _extract_styles(primary_header)
		scaled_primary_styles = {}
		for style_name, style_line in primary_styles.items():
			if scale != 1.0:
				# Scale font size (field index 2 after "Style: Name,")
				parts = style_line.split(",")
				if len(parts) >= 3:
					try:
						old_size = float(parts[2])
						parts[2] = str(int(old_size * scale))
						style_line = ",".join(parts)
					except ValueError:
						pass
			scaled_primary_styles[style_name] = style_line
		
		# Extract secondary styles
		secondary_styles = _extract_styles(secondary_header)
		
		# Merge styles: primary (scaled) + secondary (keep secondary on conflict, except our styles)
		merged_styles = {}
		for style_name, style_line in secondary_styles.items():
			merged_styles[style_name] = style_line
		for style_name, style_line in scaled_primary_styles.items():
			if style_name not in merged_styles:
				merged_styles[style_name] = style_line
		
		# Use secondary's header as base (preserves PlayRes for hardcoded positions)
		merged_header = _rebuild_ass_header(secondary_header, merged_styles)
		
		# Merge dialogues and adjust positions for overlaps
		all_dialogues = primary_dialogues + secondary_dialogues
		all_dialogues = _adjust_overlapping_positions(all_dialogues, secondary_res_y)
		all_dialogues.sort(key=lambda line: _parse_dialogue_time(line))
		
		# Write output
		with output_path.open("w", encoding="utf-8") as fh:
			fh.writelines(merged_header)
			fh.writelines(all_dialogues)
		
		logger.debug(f"Merged ASS files: {len(primary_dialogues)} + {len(secondary_dialogues)} dialogues (scale={scale:.3f})")
	
	except Exception as e:
		logger.debug(f"Error merging ASS subtitles: {e}")
		raise


def _parse_ass_file(file_path: Path) -> tuple[list[str], list[str]]:
	"""Parse ASS file into header lines and dialogue lines.
	
	Returns:
		Tuple of (header_lines, dialogue_lines)
	"""
	with file_path.open("r", encoding="utf-8") as fh:
		lines = fh.readlines()
	
	header = []
	dialogues = []
	in_events = False
	
	for line in lines:
		if line.strip() == "[Events]":
			in_events = True
			header.append(line)
		elif in_events and line.startswith("Dialogue:"):
			dialogues.append(line)
		elif in_events and line.startswith("Format:"):
			header.append(line)
		elif not in_events or (in_events and not line.startswith("Dialogue:")):
			header.append(line)
	
	return header, dialogues


def _extract_styles(header_lines: list[str]) -> dict[str, str]:
	"""Extract style definitions from ASS header.
	
	Returns:
		Dict mapping style name to full style line
	"""
	styles = {}
	for line in header_lines:
		if line.startswith("Style:"):
			parts = line.split(",", 1)
			if len(parts) == 2:
				style_name = parts[0].replace("Style:", "").strip()
				styles[style_name] = line
	return styles


def _rebuild_ass_header(primary_header: list[str], merged_styles: dict[str, str]) -> list[str]:
	"""Rebuild ASS header with merged styles, preserving primary layout.
	
	Replaces all Style: lines in primary header with merged styles.
	Styles are inserted after the Format line (required by ASS spec).
	"""
	output = []
	in_styles_section = False
	styles_inserted = False
	
	for line in primary_header:
		if line.strip() == "[V4+ Styles]":
			output.append(line)
			in_styles_section = True
		elif in_styles_section and line.startswith("Style:"):
			# Skip old style lines (will insert merged styles after Format)
			continue
		elif in_styles_section and line.startswith("Format:"):
			# Keep Format line, then insert all merged styles after it
			output.append(line)
			for style_line in merged_styles.values():
				output.append(style_line)
			styles_inserted = True
		elif in_styles_section and line.startswith("["):
			# Next section - styles section ends
			in_styles_section = False
			output.append(line)
		else:
			output.append(line)
	
	return output


def _parse_ass_time(time_str: str) -> float:
	"""Parse ASS timestamp (H:MM:SS.cc) to seconds."""
	try:
		hours, remainder = time_str.split(":")
		minutes, seconds = remainder.split(":")
		return int(hours) * 3600 + int(minutes) * 60 + float(seconds)
	except (ValueError, IndexError):
		return 0.0


def _parse_dialogue_time(dialogue_line: str) -> float:
	"""Extract start time from ASS Dialogue line for sorting.
	
	Format: Dialogue: Layer,Start,End,Style,...
	Start/End are in H:MM:SS.cc format
	
	Returns:
		Start time in seconds as float
	"""
	try:
		parts = dialogue_line.split(",", 3)
		if len(parts) >= 2:
			return _parse_ass_time(parts[1].strip())
	except (ValueError, IndexError):
		pass
	return 0.0


def _adjust_overlapping_positions(dialogues: list[str], play_res_y: int = 1080) -> list[str]:
	"""Adjust vertical margin for non-ClosedCaptions dialogues that overlap with ClosedCaptions.
	
	When Signs/other styles overlap with ClosedCaptions, push them toward center
	to create better visual separation.
	"""
	# Parse all dialogues to extract timing and style
	parsed = []
	for line in dialogues:
		if not line.startswith("Dialogue:"):
			continue
		parts = line.split(",", 9)
		if len(parts) < 10:
			parsed.append((line, 0.0, 0.0, "Unknown"))
			continue
		start = _parse_ass_time(parts[1].strip())
		end = _parse_ass_time(parts[2].strip())
		style = parts[3].strip()
		parsed.append((line, start, end, style))
	
	# Find ClosedCaptions time intervals
	cc_intervals = [(start, end) for (_, start, end, style) in parsed if style == "ClosedCaptions"]
	
	# Adjust non-ClosedCaptions that overlap with CC
	adjusted = []
	# Move Signs ~15% down from top toward center when overlapping
	center_margin = int(play_res_y * 0.15)
	
	for (line, start, end, style) in parsed:
		if style not in ("ClosedCaptions", "Unknown"):
			# Check for time overlap with any CC interval
			overlaps = any(
				not (end <= cc_start or start >= cc_end)
				for (cc_start, cc_end) in cc_intervals
			)
			if overlaps:
				# Increase MarginV (index 7) to push toward center
				parts = line.split(",", 9)
				if len(parts) >= 10:
					parts[7] = str(center_margin)
					line = ",".join(parts)
		adjusted.append(line)
	
	return adjusted


def _normalize_audio(audio_chunk: 'np.ndarray', sr: int = 16000) -> 'np.ndarray':
	"""Apply loudness normalization to audio chunk using ffmpeg loudnorm.
	
	Normalizes audio to EBU R128 standard for consistent levels.
	Returns normalized audio as float32 numpy array.
	"""
	import numpy as np
	
	# Skip if chunk is too short (< 0.1s)
	if len(audio_chunk) < sr * 0.1:
		return audio_chunk
	
	try:
		# Write chunk to temp file
		with tempfile.NamedTemporaryFile(suffix="_in.wav", delete=False) as tmp_in:
			tmp_in_path = tmp_in.name
		with tempfile.NamedTemporaryFile(suffix="_out.wav", delete=False) as tmp_out:
			tmp_out_path = tmp_out.name
		
		# Convert float32 [-1, 1] to int16 for WAV
		import scipy.io.wavfile as wav
		audio_int16 = (audio_chunk * 32767).astype(np.int16)
		wav.write(tmp_in_path, sr, audio_int16)
		
		# Apply loudnorm filter
		result = subprocess.run(
			[
				"ffmpeg", "-y", "-i", tmp_in_path,
				"-af", "highpass=f=80,loudnorm=I=-16:TP=-1.5:LRA=11",
				"-ar", str(sr), "-ac", "1",
				"-c:a", "pcm_s16le",
				tmp_out_path
			],
			capture_output=True,
			timeout=30
		)
		
		if result.returncode == 0 and Path(tmp_out_path).exists():
			# Read normalized audio
			norm_sr, norm_audio = wav.read(tmp_out_path)
			# Convert back to float32 [-1, 1]
			normalized = norm_audio.astype(np.float32) / 32767.0
			return normalized
		else:
			logger.debug(f"loudnorm failed: {result.stderr}")
			return audio_chunk
		
	except Exception as e:
		logger.debug(f"Error normalizing audio: {e}")
		return audio_chunk
	finally:
		# Cleanup temp files
		for p in [tmp_in_path, tmp_out_path]:
			try:
				Path(p).unlink(missing_ok=True)
			except:
				pass


def _detect_silence_boundaries(chunk: list[float], sr: int = 16000, threshold: float = 0.01) -> tuple[int, int]:
	"""Detect leading and trailing silence in audio chunk.
	
	Returns sample indices (start_sample, end_sample) excluding silence.
	Samples below threshold amplitude are considered silence.
	"""
	import numpy as np
	audio = np.array(chunk)
	rms = np.sqrt(np.mean(audio ** 2))
	
	# Find first sample above threshold
	start_idx = 0
	for i, sample in enumerate(audio):
		if abs(sample) > threshold * rms:
			start_idx = max(0, i - int(0.05 * sr))  # 50ms before speech starts
			break
	
	# Find last sample above threshold
	end_idx = len(audio)
	for i in range(len(audio) - 1, -1, -1):
		if abs(audio[i]) > threshold * rms:
			end_idx = min(len(audio), i + int(0.05 * sr))  # 50ms after speech ends
			break
	
	return start_idx, end_idx


# Global Silero VAD model (lazy loaded)
_silero_vad_model = None
_silero_get_speech_timestamps = None

def _check_speech_with_silero(audio_chunk: 'np.ndarray', sr: int = 16000, threshold: float = 0.5) -> tuple[bool, float]:
	"""Check if audio chunk contains speech using Silero VAD.
	
	Args:
		audio_chunk: Audio samples as numpy array (float32, mono)
		sr: Sample rate (must be 16000 for Silero)
		threshold: Speech probability threshold (0.0-1.0)
	
	Returns:
		Tuple of (has_speech: bool, max_speech_prob: float)
	"""
	global _silero_vad_model, _silero_get_speech_timestamps
	
	# Lazy load Silero VAD model
	if _silero_vad_model is None:
		logger.debug("Loading Silero VAD model...")
		_silero_vad_model, utils = torch.hub.load(
			repo_or_dir='snakers4/silero-vad',
			model='silero_vad',
			force_reload=False,
			trust_repo=True
		)
		_silero_get_speech_timestamps = utils[0]  # get_speech_timestamps function
		logger.debug("Silero VAD model loaded")
	
	# Convert numpy to torch tensor
	audio_tensor = torch.from_numpy(audio_chunk).float()
	
	# Get speech timestamps (returns list of {start, end} dicts)
	_silero_vad_model.reset_states()
	speech_timestamps = _silero_get_speech_timestamps(
		audio_tensor,
		_silero_vad_model,
		sampling_rate=sr,
		threshold=threshold,
		min_speech_duration_ms=100,
		min_silence_duration_ms=100,
	)
	
	has_speech = len(speech_timestamps) > 0
	
	# Calculate speech ratio as proxy for confidence (total speech duration / total duration)
	if has_speech:
		total_speech_samples = sum(ts['end'] - ts['start'] for ts in speech_timestamps)
		speech_ratio = total_speech_samples / len(audio_chunk)
	else:
		speech_ratio = 0.0
	
	return has_speech, speech_ratio


def _get_audio_streams(video_path: Path) -> dict:
	"""Query video file for audio streams using ffprobe.
	
	Returns dict with audio stream count as key:
	{0: {'language': 'eng'}, 1: {'language': 'jpn'}}
	"""
	try:
		result = subprocess.run(
			[
				"ffprobe", "-v", "quiet",
				"-print_format", "json",
				"-show_streams",
				str(video_path)
			],
			capture_output=True,
			text=True,
			timeout=10
		)
		if result.returncode != 0:
			logger.debug(f"ffprobe error: {result.stderr}")
			return {}
		
		data = json.loads(result.stdout)
		audio_streams = {}
		audio_count = 0
		for stream in data.get('streams', []):
			if stream.get('codec_type') == 'audio':
				language = stream.get('tags', {}).get('language', 'unknown')
				audio_streams[audio_count] = {'language': language}
				audio_count += 1
		
		return audio_streams
	
	except Exception as e:
		logger.debug(f"Error querying audio streams: {e}")
		return {}

def _extract_audio_from_video(video_path: Path, output_audio_path: Path) -> bool:
	"""Extract English audio from video file, or first audio track if no English.
	
	Returns True if successful, False otherwise.
	"""
	audio_streams = _get_audio_streams(video_path)
	
	if not audio_streams:
		logger.basic(f"-- No audio streams found in {video_path.name}")
		return False
	
	# Look for English audio stream
	english_stream_idx = None
	for stream_idx, info in audio_streams.items():
		if info['language'].lower().startswith('en'):
			english_stream_idx = stream_idx
			break
	
	# Fallback to first audio stream
	if english_stream_idx is None:
		english_stream_idx = min(audio_streams.keys())
		logger.basic(f"-- No English audio found, using first audio track (index {english_stream_idx})")
	
	logger.basic(f"-- Extracting audio stream {english_stream_idx} from {video_path.name}")
	
	try:
		result = subprocess.run(
			[
				"ffmpeg", "-i", str(video_path),
				"-map", f"0:a:{english_stream_idx}?",
				"-vn", "-c:a", "pcm_s16le",
				"-ar", "16000", "-ac", "1",
				"-y",  # Overwrite output
				str(output_audio_path)
			],
			capture_output=True,
			text=True,
			timeout=600  # 10 minute timeout
		)
		
		if result.returncode != 0:
			logger.debug(f"ffmpeg error: {result.stderr}")
			return False
		
		if output_audio_path.exists():
			logger.debug(f"Audio extracted: {output_audio_path}")
			return True
		else:
			logger.basic(f"-- Audio extraction failed for {video_path.name}")
			return False
	
	except subprocess.TimeoutExpired:
		logger.basic(f"-- Audio extraction timeout for {video_path.name}")
		return False
	except Exception as e:
		logger.debug(f"Error extracting audio: {e}")
		return False

def _get_context(args) -> str:
	"""Extract context from args using priority: gemini > anilist."""
	initial_context = ""
	context_providers = [
		("Gemini", args.gemini_context, get_gemini_context),
		("AniList", args.http_context, get_http_context),
	]
	
	# Try each context provider in order, with fallback
	for idx, (provider_name, show_name, fetch_func) in enumerate(context_providers):
		if not show_name:
			continue
			
		logger.basic(f"-- Fetching context for: {show_name} ({provider_name}) --")
		initial_context = fetch_func(show_name)
		
		if initial_context:
			logger.basic(f"-- {provider_name} context loaded: {len(initial_context)} chars --")
			logger.debug(f"Context: {initial_context}")
			logger.debug(timer.checkpoint("Context fetching complete"))

			break
		elif idx < len(context_providers) - 1 and context_providers[idx + 1][1]:
			logger.basic(f"-- No {provider_name} context loaded, trying next provider --")
		else:
			logger.basic(f"-- No {provider_name} context loaded (API error or not found) --")
	return initial_context

def _print_gpu_memory() -> None:
	"""Print GPU memory usage using nvidia-smi."""
	try:
		result = subprocess.run(
			["nvidia-smi", "--query-gpu=memory.used,memory.total", "--format=csv,noheader,nounits"],
			capture_output=True,
			text=True,
			timeout=5
		)
		used, total = result.stdout.strip().split(", ")
		print(f"GPU Memory (nvidia-smi): {float(used)/1024:.2f} GB / {float(total)/1024:.2f} GB")
	except Exception as e:
		print(f"Could not get GPU memory: {e}")

# ============================================================================
# PUBLIC FUNCTIONS
# ============================================================================

def get_http_context(anime_title: str, limit: int = 900) -> str:
	"""Fetch anime character names and metadata from AniList API for Whisper context."""
	import requests
	
	url = 'https://graphql.anilist.co'
	query = '''
	query ($search: String) {
	  Media (search: $search, type: ANIME) {
	    title { romaji english }
	    tags { name }
	    characters (sort: ROLE, perPage: 25) {
	      nodes { name { full } }
	    }
	  }
	}
	'''
	
	variables = {'search': anime_title}
	
	try:
		response = requests.post(url, json={'query': query, 'variables': variables})
		data = response.json()['data']['Media']
		
		# Build list from Title, Characters, and Tags
		prompt_parts = []
		prompt_parts.append(data['title']['romaji'])
		if data['title']['english']:
			prompt_parts.append(data['title']['english'])
		
		# Add character names
		prompt_parts.extend([c['name']['full'] for c in data['characters']['nodes']])
		
		# Join into comma-separated string and deduplicate
		full_prompt = ", ".join(list(dict.fromkeys(prompt_parts)))
		
		# Truncate to limit (ensuring it ends at a clean comma if possible)
		if len(full_prompt) > limit:
			truncated = full_prompt[:limit]
			return truncated[:truncated.rfind(',')]
		
		return full_prompt
		
	except Exception as e:
		logger.debug(f"Error fetching anime context: {e}")
		return ""

def get_gemini_context(show_name: str, char_limit: int = 900) -> str:
	"""Fetch character names and concepts from Gemini API for context.
	
	Caches responses in contexts/ directory to avoid hitting API rate limits.
	"""
	# Setup cache directory and file path
	cache_dir = Path(__file__).parent / "contexts"
	cache_dir.mkdir(exist_ok=True)
	cache_filename = sanitize_filename(show_name) + ".txt"
	cache_path = cache_dir / cache_filename
	
	# Check cache first
	if cache_path.exists():
		logger.debug(f"Using cached Gemini context: {cache_path}")
		return cache_path.read_text(encoding="utf-8").strip()
	
	from google import genai
	from google.genai import types
	gemini_key = _config.get("tokens", "gemini_api_key", fallback=None)
	if not gemini_key:
		return ""

	client = genai.Client(api_key=gemini_key)
	
	# 1. We calculate tokens based on your character limit (roughly 4 chars per token)
	token_limit = 224 

	# 2. Strict prompt for the specific format you want
	prompt = (
		f"Provide a single comma-delimited list of the most important characters, "
		f"locations, and concepts/powers for the show '{show_name}'. "
		f"Output ONLY the list, no headers, no conversational filler. <= 900 characters."
	)

	try:
		response = client.models.generate_content(
			model="gemini-3-flash-preview",
			contents=prompt,
			config=types.GenerateContentConfig(
				# max_output_tokens=token_limit, # The API stops generating exactly here
				temperature=0.1,               # Lower temperature = more focused list
			)
		)
		
		# response.text is already a plain string
		context = response.text.strip()
		
		# Cache the response
		if context:
			cache_path.write_text(context, encoding="utf-8")
			logger.debug(f"Cached Gemini context to: {cache_path}")
		
		return context
		
	except Exception as e:
		logger.debug(f"Error fetching Gemini context: {e}")
		return ""

def diarize_audio(audio_path: str, diar_pipeline):
	"""Run pyannote diarization and return the annotation object.
	
	Preloads audio into memory to speed up the embeddings phase.
	"""
	# Preload audio into memory to avoid repeated disk I/O during embeddings
	logger.debug(f"Preloading audio from {audio_path}...")
	waveform, sample_rate = torchaudio.load(audio_path)
	
	# Construct the dict expected by pyannote (keeps waveform on CPU; 
	# pipeline moves chunks to GPU internally)
	audio_in_memory = {
		"waveform": waveform,
		"sample_rate": sample_rate
	}
	logger.debug(f"Audio preloaded: {waveform.shape}, {sample_rate}Hz")

	with ProgressHook() as hook:
		result = diar_pipeline(audio_in_memory, hook=hook)

	if logger.debug_enabled:
		for idx, (turn, speaker) in enumerate(result.speaker_diarization, start=1):
			duration = turn.end - turn.start
			logger.debug(f"Diarization segment {idx}: {turn.start:.2f}s - {turn.end:.2f}s ({duration:.2f}s) Speaker: {speaker}")
	
	return result


def isolate_vocals(audio_path: Path) -> Path:
	"""Isolate vocals using audio-separator and return path to vocals audio."""
	from audio_separator.separator import Separator

	# Configure audio-separator logging based on debug flag
	if logger.debug_enabled:
		log_level = logging.INFO
	else:
		log_level = logging.WARNING

	# Get model directory from config (defaults to /tmp/audio-separator-models/)
	model_dir = _config.get("audio-separator", "model_dir", fallback=None)

	audio_str = str(audio_path)
	base_name = os.path.splitext(audio_str)[0]
	vocals_path = Path(f"{base_name}_vocals.wav")

	sep = Separator(
		log_level=log_level,
		output_single_stem="Vocals",
		model_file_dir=model_dir,
		sample_rate=16000,
		output_format="WAV",
	)
	sep.load_model(model_filename="vocals_mel_band_roformer.ckpt")
	output_files = sep.separate(audio_str)

	if output_files:
		# Find the file with "Vocals" in the name (case-insensitive)
		vocals_file = None
		for f in output_files:
			if "vocals" in Path(f).name.lower():
				vocals_file = Path(f)
				break
		
		if vocals_file:
			vocals_file.rename(vocals_path)
			logger.basic(f"-- Vocals isolated at: {vocals_path}")
			return vocals_path
		else:
			logger.basic(f"-- Warning: No vocals file found in outputs: {[Path(f).name for f in output_files]}")
			logger.basic("-- Using original audio")

	logger.basic("-- audio-separator returned no outputs; using original audio")
	return Path(audio_str)


def transcribe_full_audio(
	audio_path: Path,
	model: WhisperModel,
	beam_size: int,
	vad_filter: bool,
	word_timestamps: bool,
	words_path: Path | None,
) -> list[TranscribedSegment]:
	"""Transcribe the entire audio file directly with faster-whisper."""
	segments_iter, info = model.transcribe(
		str(audio_path),
		beam_size=beam_size,
		vad_filter=vad_filter,
		word_timestamps=word_timestamps,
	)
	segments = list(segments_iter)

	if word_timestamps and words_path:
		_write_words_json(segments, words_path)

	print(f"Detected language: {info.language} (prob={info.language_probability:.3f})")

	return [
		TranscribedSegment(start=seg.start, end=seg.end, text=seg.text)
		for seg in segments
	]


def transcribe_with_diarization(
	audio_path: Path,
	model: WhisperModel,
	beam_size: int,
	vad_filter: bool,
	word_timestamps: bool,
	diar_pipeline,
	initial_context: str = "",
	debug_audio_dir: Path | None = None,
) -> list[TranscribedSegment]:
	"""Transcribe audio using pyannote diarization segments with silence trimming.
	
	Args:
		debug_audio_dir: If set, save processed audio chunks to this directory for debugging.
	"""

	logger.basic("-- Running Diarization --")
	logger.debug(_print_gpu_memory())
	
	diarization = diarize_audio(str(audio_path), diar_pipeline)
	logger.debug(timer.checkpoint("Diarization complete"))
	logger.basic("-- Diarization Complete --")
	logger.debug(_print_gpu_memory())
	
	# Free diarization GPU memory
	gc.collect()
	torch.cuda.empty_cache()
	logger.basic("-- Freed GPU Memory --")
	logger.debug(_print_gpu_memory())
	
	logger.basic("-- Load Audio / resample --")
	# Load audio once
	waveform, sr = torchaudio.load(str(audio_path))
	resample = torchaudio.transforms.Resample(sr, 16000)

	out_segments = []
	logger.debug(timer.checkpoint("Audio loaded"))
	logger.basic("-- Load Audio / resample complete --")

	# Collect all turns first to detect overlaps
	turns_list = list(diarization.speaker_diarization)
	
	logger.basic("-- Starting transcription of diarization segments --")
	for idx, (turn, speaker) in enumerate(turns_list, start=1):
		# Skip very short segments (< 0.2s) - prone to hallucination
		segment_duration = turn.end - turn.start
		if segment_duration < 0.2:
			logger.debug(f"Skipping segment {idx} (too short: {segment_duration:.2f}s)")
			continue

		# Extract full chunk from diarization boundaries
		start_sample = int(turn.start * sr)
		end_sample = int(turn.end * sr)
		chunk = waveform[:, start_sample:end_sample]
		if chunk.shape[0] > 1:
			chunk = chunk.mean(dim=0, keepdim=True)
		chunk_16k = resample(chunk).squeeze().to(torch.float32).numpy()

		# Apply loudness normalization if enabled
		loudnorm_enabled = _config.getboolean("detection", "loudnorm", fallback=True)
		if loudnorm_enabled:
			logger.basic(f"- performing loudness normalization against segment {idx} -")
			chunk_16k = _normalize_audio(chunk_16k, sr=16000)

		# Detect and trim leading/trailing silence
		silence_start, silence_end = _detect_silence_boundaries(chunk_16k, sr=16000)
		trim_offset = silence_start / 16000  # Convert to seconds
		trimmed_chunk = chunk_16k[silence_start:silence_end]
		
		# Adjust effective start to account for trimmed silence
		effective_start = turn.start + trim_offset

		# Save debug audio chunk if requested (saves what Silero will analyze)
		if debug_audio_dir:
			import numpy as np
			import scipy.io.wavfile as wav
			# Build filename: {audio_stem}[_loudnorm]_segment{idx}.wav
			loudnorm_suffix = "_loudnorm" if loudnorm_enabled else ""
			debug_filename = f"{audio_path.stem}{loudnorm_suffix}_segment{idx:03d}.wav"
			debug_path = debug_audio_dir / debug_filename
			# Convert float32 [-1, 1] to int16 for WAV
			audio_int16 = (trimmed_chunk * 32767).astype(np.int16)
			wav.write(str(debug_path), 16000, audio_int16)
			logger.debug(f"Saved debug audio: {debug_path.name}")

		# Pre-check with Silero VAD before transcription (controlled by --vad-filter arg)
		if vad_filter:
			# Pad audio with silence to help VAD detect onset (speech starting at 0.0s confuses VAD)
			import numpy as np
			silero_padding_ms = _config.getfloat("detection", "silero_padding_ms", fallback=500.0)
			padding_samples = int(silero_padding_ms / 1000.0 * 16000)
			padded_chunk = np.concatenate([
				np.zeros(padding_samples, dtype=np.float32),  # Silence before
				trimmed_chunk,
				np.zeros(padding_samples, dtype=np.float32),  # Silence after
			])
			
			silero_threshold = _config.getfloat("detection", "silero_vad_threshold", fallback=0.5)
			has_speech, speech_prob = _check_speech_with_silero(padded_chunk, sr=16000, threshold=silero_threshold)
			
			if not has_speech:
				logger.debug(f"Skipping segment {idx} (Silero VAD detected no speech, ratio={speech_prob:.3f})")
				continue
		else:
			# No VAD pre-check, set default values for downstream filters
			has_speech = True
			speech_prob = 1.0

		# Format timestamp as HH:MM:SS for easy video seeking
		ts_hours, ts_rem = divmod(int(turn.start), 3600)
		ts_mins, ts_secs = divmod(ts_rem, 60)
		ts_str = f"{ts_hours:02}:{ts_mins:02}:{ts_secs:02}"
		
		logger.debug(f"Processing segment {idx} @ {ts_str}...")
		logger.debug(f"Original: {turn.start:.3f}s-{turn.end:.3f}s | Trimmed: {trim_offset:.3f}s silence removed")
		logger.debug(f"Silero VAD: has_speech={has_speech}, speech_ratio={speech_prob:.3f}")
		logger.debug(_print_gpu_memory())
		
		transcribe_params = {
			"beam_size": beam_size,
			"language": "en",
			"word_timestamps": word_timestamps,
			"condition_on_previous_text": True,
			"no_speech_threshold": 0.6,
			"compression_ratio_threshold": 2.4,
			"hallucination_silence_threshold": 0.5,
			"temperature": [0.0, 0.1],
			"repetition_penalty": 1,
			"best_of": 5,
			"patience": 1.2,
		}
		
		if initial_context:
			transcribe_params["initial_prompt"] = initial_context
		
		seg_iter, _ = model.transcribe(trimmed_chunk, **transcribe_params)
			
		for seg in seg_iter:
			text = seg.text.strip()
			
			# Log confidence metrics to help diagnose hallucinations
			no_speech_prob = getattr(seg, 'no_speech_prob', None)
			avg_logprob = getattr(seg, 'avg_logprob', None)
			nsp_str = f"{no_speech_prob:.3f}" if no_speech_prob is not None else "N/A"
			alp_str = f"{avg_logprob:.3f}" if avg_logprob is not None else "N/A"
			logger.debug(f"Segment text: '{text}' | no_speech_prob: {nsp_str} | avg_logprob: {alp_str}")
			
			# Hallucination filter: low speech_ratio combined with low avg_logprob
			# Configurable thresholds from config file
			filter_speech_ratio = _config.getfloat("detection", "filter_speech_ratio", fallback=0.700)
			filter_avg_logprob = _config.getfloat("detection", "filter_avg_logprob", fallback=-0.500)
			
			if (speech_prob < filter_speech_ratio and 
				avg_logprob is not None and avg_logprob < filter_avg_logprob):
				logger.debug(f"Skipping potential hallucination (speech_ratio={speech_prob:.3f} < {filter_speech_ratio} AND avg_logprob={avg_logprob:.3f} < {filter_avg_logprob}): '{text}'")
				continue
			
			# Rule 2: Ultra-low confidence filter - very uncertain transcription with non-speech detected
			filter_ultra_low_logprob = _config.getfloat("detection", "filter_ultra_low_logprob", fallback=-1.0)
			filter_no_speech_prob = _config.getfloat("detection", "filter_no_speech_prob", fallback=0.010)
			
			if (avg_logprob is not None and avg_logprob < filter_ultra_low_logprob and
				no_speech_prob is not None and no_speech_prob > filter_no_speech_prob):
				logger.debug(f"Skipping ultra-low confidence (avg_logprob={avg_logprob:.3f} < {filter_ultra_low_logprob} AND no_speech_prob={no_speech_prob:.3f} > {filter_no_speech_prob}): '{text}'")
				continue
			
			# Skip empty or suspiciously short text
			if not text or len(text) < 2:
				continue
			
			# Limit excessive character repetition (e.g., "HEEEEE..." to max 10 repeated chars)
			def limit_repetition(text: str, max_repeat: int = 10) -> str:
				"""Limit consecutive character repetition to max_repeat."""
				return re.sub(r'(.)\1{' + str(max_repeat) + r',}', lambda m: m.group(1) * max_repeat, text)
			
			text = limit_repetition(text)
			
			# Skip common hallucination phrases
			hallucination_phrases = [
				"thank you for watching",
				"thanks for watching",
				"subscribe",
				"like and subscribe",
				"Subtitles by the Amara.org community",
				"see you next time",
			]
			if any(phrase in text.lower() for phrase in hallucination_phrases):
				logger.debug(f"Skipping hallucination phrase: {text}")
				continue
			
			# Skip text that is only ellipsis or punctuation
			if text.strip("., !?") == "":
				logger.debug(f"Skipping punctuation-only: {text}")
				continue

			# Adjust timestamps: relative to trimmed chunk + offset from original boundary
			final_start = effective_start + seg.start
			final_end = effective_start + seg.end
			logger.debug(f"Start: {final_start:.3f}s, End: {final_end:.3f}s, Text: {text}")
			out_segments.append(TranscribedSegment(
				start=final_start,
				end=final_end,
				text=text,
				speaker=None,
			))

		logger.debug(f"Segment {idx} complete")
		torch.cuda.empty_cache()

	# Sort by start time
	out_segments.sort(key=lambda s: s.start)
	
	# Merge overlapping segments for proper subtitle display
	out_segments = _merge_overlapping_segments(out_segments)
	logger.debug(timer.checkpoint("Diarization transcription complete"))
	return out_segments

def transcribe_to_subtitles(
	audio_path: Path,
	video_path: Path,
	model: WhisperModel,
	beam_size: int,
	vad_filter: bool,
	word_timestamps: bool,
	words_path: Path | None,
	output_path: Path,
	diarise: bool,
	vocals: bool,
	initial_context: str = "",
	diar_pipeline=None,
	extract_subtitle: str | None = None,
	subtitle_lead_ms: float = 400.0,
	subtitle_lag_ms: float = 600.0,
	debug_audio_dir: Path | None = None,
) -> Path:
	"""Main transcription orchestrator that outputs to SRT or ASS format.
	
	Format is determined by output_path extension (.srt or .ass).
	Defaults to ASS if no recognized extension.
	Optionally extracts and merges subtitle tracks from the MKV.
	
	Args:
		subtitle_lead_ms: Start text this many ms before audio starts (default: 400ms)
		subtitle_lag_ms: Keep text this many ms after audio ends (default: 600ms)
	"""
	# Determine output format from file extension
	output_format = output_path.suffix.lower()

	# Isolate vocals FIRST so both diarization and transcription work on cleaner audio
	if vocals:
		logger.basic("-- Isolating vocals with audio-separator --")
		audio_path = isolate_vocals(audio_path)
		logger.debug(timer.checkpoint("Vocals isolated"))

	logger.debug(f"Current Audio file: {audio_path}")

	if diarise:
		# Diarization path ignores word_timestamps
		segments = transcribe_with_diarization(audio_path, model, beam_size, vad_filter, word_timestamps, diar_pipeline, initial_context, debug_audio_dir)
	else:
		logger.basic("-- Transcribing Full Audio --")
		segments = transcribe_full_audio(
			audio_path, model, beam_size, vad_filter, word_timestamps, words_path
		)

	# Apply timing adjustments (convert ms to seconds)
	# Config values used as defaults, CLI args can override
	config_lead = _config.getfloat("transcription", "subtitle_before_padding", fallback=400.0)
	config_lag = _config.getfloat("transcription", "subtitle_after_padding", fallback=600.0)
	
	# Use CLI args if provided, otherwise fall back to config
	lead_offset = (subtitle_lead_ms if subtitle_lead_ms != 400.0 else config_lead) / 1000.0
	lag_offset = (subtitle_lag_ms if subtitle_lag_ms != 600.0 else config_lag) / 1000.0
	
	for seg in segments:
		seg.start = max(0, seg.start - lead_offset)  # Start earlier
		seg.end = seg.end + lag_offset  # End later

	# Write in appropriate format
	if output_format == ".srt":
		_write_srt(segments, output_path)
		logger.basic(f"Wrote SRT: {output_path}")
	else:  # ASS format
		mkv_title = _get_mkv_title(video_path)
		mkv_resolution = _get_mkv_resolution(video_path)
		_write_ass(segments, output_path, mkv_title, mkv_resolution)
		logger.basic(f"Wrote ASS: {output_path}")
		
		# Extract and merge external subtitle if requested
		if extract_subtitle:
			extracted_path = _extract_subtitle_from_mkv(video_path, extract_subtitle)
			if extracted_path:
				# Convert to styled ASS if not already ASS
				if extracted_path.suffix.lower() != ".ass":
					ass_temp = extracted_path.parent / f"{extracted_path.stem}_signs.ass"
					_convert_secondary_to_signs_ass(extracted_path, ass_temp, mkv_resolution)
					extracted_path.unlink()
					extracted_path = ass_temp
				
				# Merge with transcription
				merged_path = output_path.parent / f"{output_path.stem}_merged.ass"
				_merge_ass_subtitles(output_path, extracted_path, merged_path)
				output_path.unlink()
				merged_path.rename(output_path)
				extracted_path.unlink()
				logger.basic(f"Merged '{extract_subtitle}' subtitles into {output_path.name}")
	
	return output_path


def _convert_subtitle_to_ass(input_path: Path, output_path: Path) -> None:
	"""Convert subtitle file to ASS format using ffmpeg.
	
	Args:
		input_path: Path to input subtitle file (SRT, SSA, etc)
		output_path: Path to output ASS file
	"""
	try:
		subprocess.run(
			["ffmpeg", "-y", "-i", str(input_path), str(output_path)],
			capture_output=True,
			timeout=30,
			check=True
		)
		logger.debug(f"Converted {input_path.name} to ASS format")
	except Exception as e:
		logger.debug(f"Error converting to ASS: {e}")
		raise


def _convert_secondary_to_signs_ass(input_path: Path, output_path: Path, mkv_resolution: tuple[int, int]) -> None:
	"""Convert secondary subtitle (Signs/Songs) to ASS with Signs style.
	
	Used when secondary subtitle is SRT or other non-ASS format.
	Applies top-center positioning with subtle aqua color.
	"""
	play_res_x, play_res_y = mkv_resolution
	signs_font_size = int(44 * play_res_y / 1080)  # Signs: 44pt at 1080p (slightly larger)
	
	# Convert to ASS first via ffmpeg
	temp_ass = input_path.parent / f"{input_path.stem}_temp_convert.ass"
	_convert_subtitle_to_ass(input_path, temp_ass)
	
	# Parse dialogues
	_, dialogues = _parse_ass_file(temp_ass)
	temp_ass.unlink()
	
	# Build header with Signs style
	ass_header = f"""[Script Info]
; Secondary subtitle converted by transcribe_faster_whisper.py
ScriptType: v4.00+
PlayResX: {play_res_x}
PlayResY: {play_res_y}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Signs,Arial,{signs_font_size},&H00FFFFC8,&H000000FF,&H64000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,8,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
	
	# Remap all dialogues to Signs style
	restyled_dialogues = []
	for line in dialogues:
		if line.startswith("Dialogue:"):
			parts = line.split(",", 9)
			if len(parts) >= 10:
				parts[3] = "Signs"
				restyled_dialogues.append(",".join(parts))
			else:
				restyled_dialogues.append(line)
		else:
			restyled_dialogues.append(line)
	
	with output_path.open("w", encoding="utf-8") as fh:
		fh.write(ass_header)
		fh.writelines(restyled_dialogues)
	
	logger.debug(f"Converted {input_path.name} to Signs-styled ASS: {len(restyled_dialogues)} dialogues")


def _convert_subtitle_to_styled_ass(input_path: Path, output_path: Path, mkv_title: str, mkv_resolution: tuple[int, int]) -> None:
	"""Convert subtitle to ASS with proper header styling (matching transcription output).
	
	Extracts dialogues from input subtitle and writes them with our standard ASS header.
	"""
	play_res_x, play_res_y = mkv_resolution
	font_size = int(38 * play_res_y / 1080)  # ClosedCaptions: 38pt at 1080p
	signs_font_size = int(44 * play_res_y / 1080)  # Signs: 44pt at 1080p (slightly larger)
	
	# If already ASS, parse and restyle; otherwise convert first
	if input_path.suffix.lower() == '.ass':
		temp_ass = input_path
	else:
		# Convert to ASS first via ffmpeg
		temp_ass = input_path.parent / f"{input_path.stem}_temp_convert.ass"
		_convert_subtitle_to_ass(input_path, temp_ass)
	
	# Parse dialogues from the ASS file
	_, dialogues = _parse_ass_file(temp_ass)
	
	# Clean up temp file if we created it
	if temp_ass != input_path and temp_ass.exists():
		temp_ass.unlink()
	
	# Build our standard ASS header
	ass_header = f"""[Script Info]
; Script generated by transcribe_faster_whisper.py
Title: {mkv_title}
ScriptType: v4.00+
Collisions: Normal
PlayResX: {play_res_x}
PlayResY: {play_res_y}
Timer: 100.0000

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,{font_size},&H00FFFFFF,&H000000FF,&H64000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: ClosedCaptions,Arial,{font_size},&H00FFFFFF,&H000000FF,&H64000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: Signs,Arial,{signs_font_size},&H00FFFFC8,&H000000FF,&H64000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,8,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
	
	# Remap dialogues to use ClosedCaptions style
	restyled_dialogues = []
	for line in dialogues:
		# Parse dialogue: Dialogue: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text
		if line.startswith("Dialogue:"):
			parts = line.split(",", 9)  # Split into max 10 parts
			if len(parts) >= 10:
				# Replace style (index 3) with ClosedCaptions
				parts[3] = "ClosedCaptions"
				restyled_dialogues.append(",".join(parts))
			else:
				restyled_dialogues.append(line)
		else:
			restyled_dialogues.append(line)
	
	# Write output
	with output_path.open("w", encoding="utf-8") as fh:
		fh.write(ass_header)
		fh.writelines(restyled_dialogues)
	
	logger.debug(f"Converted {input_path.name} to styled ASS: {len(restyled_dialogues)} dialogues")


def process_dubtitle(
	video_path: Path,
	output_path: Path,
	dubtitle_pattern: str,
	extract_subtitle: str | None = None,
) -> bool:
	"""Process video using existing subtitle track instead of transcription.
	
	Extracts the dubtitle track, converts to styled ASS, and optionally merges
	with another subtitle track (e.g., Signs/Songs).
	
	Args:
		video_path: Path to MKV file
		output_path: Path for output ASS file
		dubtitle_pattern: Pattern to match subtitle track name
		extract_subtitle: Optional pattern for secondary subtitle to merge
	
	Returns:
		True if successful, False if dubtitle track not found
	"""
	# Extract the dubtitle track
	dubtitle_path = _extract_subtitle_from_mkv(video_path, dubtitle_pattern)
	if dubtitle_path is None:
		logger.basic(f"-- No subtitle track matching '{dubtitle_pattern}' found in {video_path.name}")
		return False
	
	logger.basic(f"-- Found dubtitle track: {dubtitle_path.name}")
	
	# Get video metadata for ASS header
	mkv_title = _get_mkv_title(video_path)
	mkv_resolution = _get_mkv_resolution(video_path)
	
	# Convert to styled ASS
	_convert_subtitle_to_styled_ass(dubtitle_path, output_path, mkv_title, mkv_resolution)
	dubtitle_path.unlink()  # Clean up extracted file
	
	logger.basic(f"-- Converted dubtitle to ASS: {output_path.name}")
	
	# Optionally merge with secondary subtitle (e.g., Signs/Songs)
	if extract_subtitle:
		extracted_path = _extract_subtitle_from_mkv(video_path, extract_subtitle)
		if extracted_path:
			# Convert to styled ASS if not already ASS
			if extracted_path.suffix.lower() != ".ass":
				ass_temp = extracted_path.parent / f"{extracted_path.stem}_signs.ass"
				_convert_secondary_to_signs_ass(extracted_path, ass_temp, mkv_resolution)
				extracted_path.unlink()
				extracted_path = ass_temp
			
			# Merge with dubtitle
			merged_path = output_path.parent / f"{output_path.stem}_merged.ass"
			_merge_ass_subtitles(output_path, extracted_path, merged_path)
			output_path.unlink()
			merged_path.rename(output_path)
			extracted_path.unlink()
			logger.basic(f"-- Merged '{extract_subtitle}' subtitles into {output_path.name}")
		else:
			logger.basic(f"-- No '{extract_subtitle}' track found to merge")
	
	return True


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("input_path", type=Path, help="Path to MKV file or directory of MKV files")
	parser.add_argument(
		"--model",
		default="Systran/faster-whisper-large-v3",
		help="Model ID to load",
	)
	parser.add_argument(
		"--compute-type",
		default="float16",
		help="Compute type (e.g., float16, float32, int8_float16)",
	)
	parser.add_argument(
		"--beam-size",
		type=int,
		default=5,
		help="Beam size for decoding",
	)
	parser.add_argument(
		"--vad-filter",
		action="store_true",
		help="Enable VAD filtering (uses Silero VAD)",
	)
	parser.add_argument(
		"--word-timestamps",
		action="store_true",
		help="Enable word-level timestamps during transcription",
	)
	parser.add_argument(
		"--words-json",
		type=Path,
		help="Optional path to write word-level timestamps JSON (requires --word-timestamps)",
	)
	parser.add_argument(
		"--format",
		default=".ass",
		choices=[".ass", ".srt"],
		help="Output subtitle format (default: .ass)",
	)
	parser.add_argument(
		"--diarise",
		action="store_true",
		help="Enable speaker diarization (ignores --vad-filter and --word-timestamps)",
	)
	parser.add_argument(
		"--vocals",
		action="store_true",
		help="Isolate vocals with audio-separator before transcription",
	)
	parser.add_argument(
		"--http-context",
		type=str,
		default=None,
		help="Anime title to fetch character names from AniList API for transcription context",
	)
	parser.add_argument(
		"--gemini-context",
		type=str,
		default=None,
		help="TV show/movie name to fetch context from Gemini API for transcription",
	)
	parser.add_argument(
		"--force-recreate",
		action="store_true",
		help="Recreate subtitles even if .srt or .ass exists",
	)
	parser.add_argument(
		"--use-dubtitle",
		type=str,
		default=None,
		help="Use existing subtitle track matching this pattern as transcription (bypasses Whisper/diarization)",
	)
	parser.add_argument(
		"--extract-subtitle",
		type=str,
		default=None,
		help="Extract and merge subtitle track from MKV matching this pattern (e.g., 'Signs', 'Songs', 'CC')",
	)
	parser.add_argument(
		"--subtitle-lead-ms",
		type=float,
		default=400.0,
		help="Start subtitle text this many milliseconds before audio begins (default: 400ms)",
	)
	parser.add_argument(
		"--subtitle-lag-ms",
		type=float,
		default=600.0,
		help="Keep subtitle text this many milliseconds after audio ends (default: 600ms)",
	)
	parser.add_argument(
		"--no-cleanup",
		action="store_true",
		help="Keep temporary audio files after processing (for debugging)",
	)
	return parser.parse_args()


def main() -> None:
	logger.basic("-- Parsing Args --")
	args = parse_args()
	logger.debug(timer.checkpoint("Args parsed"))
	logger.basic("-- Parsed Args --")

	logger.basic("-- Parsing Input File/s --")
	if not args.input_path.exists():
		raise FileNotFoundError(f"Input path not found: {args.input_path}")

	# Determine and filter list of files to process
	def _has_subtitle(video_file: Path) -> bool:
		"""Check if video file has existing subtitle in the target format."""
		return video_file.with_suffix(args.format).exists()

	# Discover video files from input path
	if args.input_path.is_file():
		if args.input_path.suffix.lower() == '.mkv':
			video_files = [args.input_path]
		else:
			raise ValueError(f"Input file must be MKV format, got: {args.input_path.suffix}")
	elif args.input_path.is_dir():
		video_files = sorted(args.input_path.glob("*.mkv"))
		if not video_files:
			logger.basic(f"- No MKV files found in {args.input_path}")
			return
		logger.basic(f"- Found {len(video_files)} MKV files")
	else:
		raise ValueError(f"Input path is neither file nor directory: {args.input_path}")

	# Filter out files with existing subtitles (unless --force-recreate)
	if not args.force_recreate:
		video_files = [
			vf for vf in video_files
			if not (_has_subtitle(vf) and not logger.basic(f"- Subtitle exists for {vf.name}, skipping"))
		]
		
		if not video_files:
			logger.basic("- All files have existing subtitles, nothing to process")
			return
	logger.debug(f"- {len(video_files)} files to process after filtering existing subtitles -")
	logger.debug(timer.checkpoint("Parsed Input File/s"))
	logger.basic("-- Parsed Input File/s --")

	# === DUBTITLE PATH: Use existing subtitle track (bypasses all ML processing) ===
	if args.use_dubtitle:
		logger.basic(f"-- Dubtitle mode: Looking for '{args.use_dubtitle}' subtitle track --")
		
		for video_file in video_files:
			logger.basic(f"\n-- Processing (dubtitle): {video_file.name} --")
			output_path = video_file.with_suffix(args.format)
			
			if process_dubtitle(video_file, output_path, args.use_dubtitle, args.extract_subtitle):
				logger.basic(f"-- Completed (dubtitle): {video_file.name} --")
			else:
				logger.basic(f"-- Skipped (no matching dubtitle): {video_file.name} --")
		
		logger.basic("\n-- Dubtitle processing complete --")
		return  # Exit early, no ML processing needed

	# === TRANSCRIPTION PATH: Load models and process with Whisper ===
	logger.basic("-- Loading Whisper Model --")
	model = WhisperModel(args.model, device="cuda", compute_type=args.compute_type)
	logger.debug(timer.checkpoint("Whisper model loaded"))
	logger.basic("-- Whisper Model loaded --")

	if args.diarise:
		logger.basic("-- Importing modules for Diarization --")

		global Pipeline
		global ProgressHook
		global torch
		global torchaudio

		from pyannote.audio import Pipeline
		logger.debug(timer.checkpoint("Pipeline loaded"))
		from pyannote.audio.pipelines.utils.hook import ProgressHook
		logger.debug(timer.checkpoint("ProgressHook loaded"))
		# Suppress pyannote warnings about TF32 and std() edge cases
		warnings.filterwarnings("ignore", category=UserWarning, module="pyannote.audio")
		import torch
		logger.debug(timer.checkpoint("Torch loaded"))
		# Enable TF32 globally before any operations
		torch.backends.cuda.matmul.allow_tf32 = True
		torch.backends.cudnn.allow_tf32 = True
		torch.set_float32_matmul_precision('high')
		import torchaudio
		logger.debug(timer.checkpoint("TorchAudio loaded"))

		logger.debug(timer.checkpoint("Modules for Diarization loaded"))
		logger.basic("-- Completed Importing modules for Diarization --")
		logger.basic("-- Loading Model for Diarization --")

		hf_token = _config.get("tokens", "hf_read_token", fallback=None)
		diar_pipeline = Pipeline.from_pretrained(
			"pyannote/speaker-diarization-community-1",
			token=hf_token
		)
		# Run diarization on GPU for higher accuracy.
		diar_pipeline.to(torch.device("cuda"))
		
		# Adjust onset threshold from config to reduce false positives on non-speech audio
		# Default is 0.5; higher values require stronger speech signal
		onset_threshold = _config.getfloat("detection", "onset", fallback=0.5)
		try:
			diar_pipeline._segmentation.onset = onset_threshold
			logger.debug(f"Pyannote onset threshold set to {onset_threshold}")
		except AttributeError:
			logger.debug("Could not adjust pyannote onset threshold (API may have changed)")
		
		logger.debug(timer.checkpoint("Diarization model loaded"))
		logger.basic("-- Completed Loading Model for Diarization --")
	else:
		diar_pipeline = None
	
	# Fetch context once for all files
	initial_context = _get_context(args)

	# Initialize video handler variable
	current_video_handler = None

	# Process each video file
	for video_file in video_files:
		# Setup per-video logging if enabled
		if current_video_handler:
			remove_handler_from_logger(logger, current_video_handler)
		
		if general_handler:
			try:
				video_sanitized = sanitize_filename(video_file.name)
				video_log_path = log_dir / f"{video_sanitized}.log"
				current_video_handler = logging.FileHandler(video_log_path, encoding='utf-8')
				formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
				current_video_handler.setFormatter(formatter)
				current_video_handler.setLevel(logging.DEBUG)
				add_handler_to_logger(logger, current_video_handler)
			except Exception as e:
				logger.debug(f"Error setting up video logging: {e}")
				current_video_handler = None
		
		logger.basic(f"\n-- Processing: {video_file.name} --")
		
		# Determine output path based on format
		output_path = video_file.with_suffix(args.format)
		
		# Ensure tmp directory exists
		tmp_dir = Path("/mnt/i/python/tmp")
		tmp_dir.mkdir(parents=True, exist_ok=True)
		
		# Extract audio from video
		with tempfile.NamedTemporaryFile(suffix=".wav", delete=False, dir=str(tmp_dir)) as tmp_audio:
			audio_path = Path(tmp_audio.name)
		
		try:
			if not _extract_audio_from_video(video_file, audio_path):
				logger.basic(f"- Failed to extract audio from {video_file.name}, skipping")
				continue
			
			logger.debug(timer.checkpoint("Audio extracted"))
			
			# Transcribe the extracted audio
			transcribe_to_subtitles(
				audio_path=audio_path,
				video_path=video_file,
				model=model,
				beam_size=args.beam_size,
				vad_filter=args.vad_filter,
				word_timestamps=args.word_timestamps,
				words_path=args.words_json,
				output_path=output_path,
				diarise=args.diarise,
				vocals=args.vocals,
				initial_context=initial_context,
				diar_pipeline=diar_pipeline,
				extract_subtitle=args.extract_subtitle,
				subtitle_lead_ms=args.subtitle_lead_ms,
				subtitle_lag_ms=args.subtitle_lag_ms,
				debug_audio_dir=tmp_dir if args.no_cleanup else None,
			)
			logger.debug(timer.checkpoint(f"Transcription complete for {video_file.name}"))
			logger.basic(f"-- Completed processing: {video_file.name} --")
		
		finally:
			# Clean up extracted audio and vocals file (unless --no-cleanup)
			if not args.no_cleanup:
				if audio_path.exists():
					audio_path.unlink()
					logger.debug(f"- Cleaned up temporary audio: {audio_path}")
				
				# Clean up vocals file if it exists (created by isolate_vocals)
				vocals_path = audio_path.with_name(audio_path.stem + "_vocals.wav")
				if vocals_path.exists():
					vocals_path.unlink()
					logger.debug(f"- Cleaned up vocals audio: {vocals_path}")
			else:
				logger.debug(f"- Keeping temporary files (--no-cleanup): {audio_path}")
	
	# Clean up video handler if it exists
	if current_video_handler:
		remove_handler_from_logger(logger, current_video_handler)

if __name__ == "__main__":
	main()
